export const fishList = [
  {
    name: "イワシ",
    score: 60,
    requiredInteractions: 5,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 3,
  },
  {
    name: "タイ",
    score: 135,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 20,
  },
  {
    name: "ヒラメ",
    score: 130,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 20,
  },
  {
    name: "サンマ",
    score: 120,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 7,
  },
  {
    name: "ブリ",
    score: 122,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 10,
  },
  {
    name: "イカ",
    score: 105,
    requiredInteractions: 25,
    CatchableMinDepth: 10,
    CatchableMaxDepth: 20,
  },
  {
    name: "タコ",
    score: 98,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 3,
  },
  {
    name: "ウナギ",
    score: 137,
    requiredInteractions: 25,
    CatchableMinDepth: 25,
    CatchableMaxDepth: 80,
  },
  {
    name: "サケ",
    score: 124,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 4,
  },
  {
    name: "アジ",
    score: 118,
    requiredInteractions: 25,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 15,
  },
  {
    name: "クラゲ",
    score: 90,
    requiredInteractions: 3,
    CatchableMinDepth: 8,
    CatchableMaxDepth: 28,
  },
  {
    name: "トビウオ",
    score: 110,
    requiredInteractions: 10,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 4,
  },
  {
    name: "クリオネ",
    score: 95,
    requiredInteractions: 6,
    CatchableMinDepth: 15,
    CatchableMaxDepth: 60,
  },
  {
    name: "スズキ",
    score: 100,
    requiredInteractions: 25,
    CatchableMinDepth: 5,
    CatchableMaxDepth: 8,
  },
  {
    name: "フグ",
    score: 133,
    requiredInteractions: 10,
    CatchableMinDepth: 10,
    CatchableMaxDepth: 30,
  },
  {
    name: "カツオ",
    score: 125,
    requiredInteractions: 25,
    CatchableMinDepth: 4,
    CatchableMaxDepth: 10,
  },
  {
    name: "ウミガメ",
    score: 160,
    requiredInteractions: 25,
    CatchableMinDepth: 3,
    CatchableMaxDepth: 20,
  },
  {
    name: "ダイオウグソクムシ",
    score: 180,
    requiredInteractions: 25,
    CatchableMinDepth: 20,
    CatchableMaxDepth: 50,
  },
  {
    name: "メンダコ",
    score: 157,
    requiredInteractions: 25,
    CatchableMinDepth: 20,
    CatchableMaxDepth: 100,
  },
  {
    name: "マグロ",
    score: 210,
    requiredInteractions: 300,
    CatchableMinDepth: 10,
    CatchableMaxDepth: 15,
  },
  {
    name: "キンメダイ",
    score: 270,
    requiredInteractions: 25,
    CatchableMinDepth: 20,
    CatchableMaxDepth: 80,
  },
  {
    name: "サメ",
    score: 150,
    requiredInteractions: 51,
    CatchableMinDepth: 3,
    CatchableMaxDepth: 15,
  },
  {
    name: "ウツボ",
    score: 140,
    requiredInteractions: 30,
    CatchableMinDepth: 6,
    CatchableMaxDepth: 14,
  },
  {
    name: "海草",
    score: 50,
    requiredInteractions: 10,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 100,
  },
  {
    name: "伊勢海老",
    score: 250,
    requiredInteractions: 20,
    CatchableMinDepth: 0,
    CatchableMaxDepth: 3,
  },
  {
    name: "マンボウ",
    score: 300,
    requiredInteractions: 45,
    CatchableMinDepth: 10,
    CatchableMaxDepth: 30,
  },
  {
    name: "カジキ",
    score: 450,
    requiredInteractions: 300,
    CatchableMinDepth: 40,
    CatchableMaxDepth: 60,
  },
  {
    name: "ザトウクジラ",
    score: 600,
    requiredInteractions: 700,
    CatchableMinDepth: 40,
    CatchableMaxDepth: 100,
  },
  {
    name: "リュウグウノツカイ",
    score: 800,
    requiredInteractions: 500,
    CatchableMinDepth: 70,
    CatchableMaxDepth: 87,
  },
  {
    name: "ダンクルオステウス",
    score: 1200,
    requiredInteractions: 999,
    CatchableMinDepth: 85,
    CatchableMaxDepth: 100,
  },
];
